name: Deploy Ionic 1 app to Azure App Service
# This workflow is triggered when pushing to a main branch
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: bestonicWebAppInTheWorld  # Set this to your app service name
  PACKAGE_PATH: './www' # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: 18.x # Set this to the node version to use
jobs:
  build-and-deploy:
    runs-on: windows-2019
    # You can use default run to set default shell to all steps
    defaults:
      run:
        shell: powershell
        # Using a specific shell https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    steps:
      - name: Checkout the latest source code
        uses: actions/checkout@v2 # For more version https://github.com/actions/checkout/releases
      - name: Use Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Gulp CLI already installed
      # https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-NodeLts.ps1
      - name: Install Bower as global tools
        run: |
          npm install -g bower
      - name: Build all Node.js projects with npm
        run: |
          bower install
          npm install
          npm run build
      - name: Deploy Azure App Service code Node.js and use IIS 10.0, Windows Server 2016
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          # Before downloading load publish profile, make sure that you have set WEBSITE_WEBDEPLOY_USE_SCM
          # in App Service Configuration to true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_54D3452FFDE24184AAF872B18ABCADD7 }}
          package: ${{ env.PACKAGE_PATH }}
